// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//testtestdeletedelete
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtKZmq3z_GoHwCen3psqWU2xKSEY_yFo',
    appId: '1:906145044028:web:5185d4feb67872eff2d539',
    messagingSenderId: '906145044028',
    projectId: 'test0-40nfoq',
    authDomain: 'test0-40nfoq.firebaseapp.com',
    storageBucket: 'test0-40nfoq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aTPmDmS3TU7y7a0pNm3bwZsfLPRU1S0',
    appId: '1:906145044028:android:70114b94abdcb6dff2d539',
    messagingSenderId: '906145044028',
    projectId: 'test0-40nfoq',
    storageBucket: 'test0-40nfoq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jCDMhp07TZXQ1tbDKtw0B0ilaU6WZb4',
    appId: '1:906145044028:ios:5a94d3318b581933f2d539',
    messagingSenderId: '906145044028',
    projectId: 'test0-40nfoq',
    storageBucket: 'test0-40nfoq.appspot.com',
    iosBundleId: 'com.cups.danmoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2jCDMhp07TZXQ1tbDKtw0B0ilaU6WZb4',
    appId: '1:906145044028:ios:380a8fce4271cf24f2d539',
    messagingSenderId: '906145044028',
    projectId: 'test0-40nfoq',
    storageBucket: 'test0-40nfoq.appspot.com',
    iosBundleId: 'com.cups.danmoa.RunnerTests',
  );
}
